/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be :

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

/* This solution make use of the fact that every third number of the Fibonacci
sequence is even */

#include <stdio.h>

#define MAX 4000000

int main(void)
{
  int a, b, c, sum;
  a = c = sum = 0;
  b = 1;

  while (a < MAX && b < MAX && c < MAX) {
    c = a + b;
    a = b + c;
    b = a + c;
    sum = sum + a;
  }
  printf("%d\n", sum);

  return 0;
}
